services:
  fsdc_api_staging:
    container_name: fsdc_api_staging
    build:
      context: .
    ports:
      - 5073:8000
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD}
      POSTGRES_DB: fsdc_db_staging
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
    labels:
        - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - postgres_network
    volumes:
      - ./data_staging:/app/data
networks:
  postgres_network:
    external: true
