services:
  postgres:
    container_name: fsdc_postgres_staging
    image: postgres:14
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432" # Optional: exposes Postgres to host at localhost:5432
    volumes:
      - pgdata_staging:/var/lib/postgresql/data
    networks:
      - postgres_network

  fsdc_api_staging:
    container_name: fsdc_api_staging
    build:
      context: .
    ports:
      - 5073:8000
    env_file:
      - .env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - postgres_network
    volumes:
      - ./data_staging:/app/data

volumes:
  pgdata_staging:


networks:
  postgres_network:
