"""Added keyword fields


Revision ID: 0b7a096c55fb
Revises: d86c516868cf
Create Date: 2025-07-11 13:20:52.743220

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0b7a096c55fb"
down_revision: Union[str, Sequence[str], None] = "d86c516868cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "researchentry",
        sa.Column(
            "main_keyword", sa.String(), nullable=False, server_default="missing"
        ),
    )
    op.add_column(
        "researchentry",
        sa.Column(
            "alternate_keywords", sa.String(), nullable=False, server_default="missing"
        ),
    )
    # Remove server_default after setting values for existing rows
    op.alter_column("researchentry", "main_keyword", server_default=None)
    op.alter_column("researchentry", "alternate_keywords", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("researchentry", "alternate_keywords")
    op.drop_column("researchentry", "main_keyword")
    # ### end Alembic commands ###
