"""Add new fields for eggplant data

Revision ID: 75253c59959d
Revises: cd1ed2244844
Create Date: 2025-06-23 07:31:07.318408

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "75253c59959d"
down_revision: Union[str, Sequence[str], None] = "cd1ed2244844"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("researchentry", sa.Column("title", sa.String(), nullable=False))
    op.add_column(
        "researchentry", sa.Column("project_summary", sa.String(), nullable=False)
    )
    op.add_column(
        "researchentry", sa.Column("time_period", sa.String(), nullable=False)
    )
    op.add_column(
        "researchentry", sa.Column("thesis_advisor_name", sa.String(), nullable=False)
    )
    op.add_column(
        "researchentry", sa.Column("thesis_advisor_email", sa.String(), nullable=False)
    )
    op.add_column(
        "researchentry", sa.Column("thesis_advisor_phone", sa.String(), nullable=False)
    )
    op.add_column(
        "researchentry", sa.Column("postal_address", sa.String(), nullable=False)
    )
    op.add_column(
        "researchentry",
        sa.Column("department_and_faculty", sa.String(), nullable=False),
    )
    op.add_column("researchentry", sa.Column("orcid", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("researchentry", "orcid")
    op.drop_column("researchentry", "department_and_faculty")
    op.drop_column("researchentry", "postal_address")
    op.drop_column("researchentry", "thesis_advisor_phone")
    op.drop_column("researchentry", "thesis_advisor_email")
    op.drop_column("researchentry", "thesis_advisor_name")
    op.drop_column("researchentry", "time_period")
    op.drop_column("researchentry", "project_summary")
    op.drop_column("researchentry", "title")
    # ### end Alembic commands ###
