"""Initial schema

Revision ID: d86c516868cf
Revises:
Create Date: 2025-06-23 08:26:27.921005

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d86c516868cf"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "codebook",
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dataset",
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "researcher",
        sa.Column("fname", sa.String(), nullable=False),
        sa.Column("lname", sa.String(), nullable=False),
        sa.Column("education", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "subdiscipline",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "researchentry",
        sa.Column("date_started", sa.Date(), nullable=False),
        sa.Column("date_ended", sa.Date(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("bibliography", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("project_summary", sa.String(), nullable=False),
        sa.Column("time_period", sa.String(), nullable=False),
        sa.Column("thesis_advisor_name", sa.String(), nullable=False),
        sa.Column("thesis_advisor_email", sa.String(), nullable=False),
        sa.Column("thesis_advisor_phone", sa.String(), nullable=False),
        sa.Column("postal_address", sa.String(), nullable=False),
        sa.Column("department_and_faculty", sa.String(), nullable=False),
        sa.Column("orcid", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("subdiscipline_id", sa.Uuid(), nullable=False),
        sa.Column("researcher_id", sa.Uuid(), nullable=False),
        sa.Column("codebook_id", sa.Uuid(), nullable=False),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["codebook_id"],
            ["codebook.id"],
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["researcher_id"],
            ["researcher.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subdiscipline_id"],
            ["subdiscipline.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("researchentry")
    op.drop_table("subdiscipline")
    op.drop_table("researcher")
    op.drop_table("dataset")
    op.drop_table("codebook")
    # ### end Alembic commands ###
